# Generated by Django 6.0.5 on 2026-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('guest_lecture', 'Guest Lecture'), ('conference', 'Conference'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
