# Generated by Django 6.0.5 on 2026-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('pub_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('book_chapter', 'Book Chapter')], default='journal', max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
