# Generated by Django 6.0.5 on 2026-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='teams_shortlisted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='winning_teams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('guest_lecture', 'Guest Lecture'), ('conference', 'Conference'), ('ideathon', 'Ideathon'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
