# Generated by Django 6.0.5 on 2026-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_event_attendees_event_registrations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodhiShalaContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodhiShalaPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('pub_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('book_chapter', 'Book Chapter')], default='journal', max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
